---
services:
  magi-docker:
    image: aaronme/magi-docker:latest
    container_name: magi-docker
    ports:
      - "8232:8232"
      - "8233:8233"
    volumes:
      - ./data:/magi/data
    restart: unless-stopped
