name: Deploy Docker Image

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-22.04
    env:
      MAGI_VERSION: '1.4.7.2'
      USERNAME: 'aaronme'
      IMAGE_NAME: 'magi-docker'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          file: ${{ env.MAGI_VERSION }}-pre/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:latest,${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:v${{ env.MAGI_VERSION }}
